# Generated by Django 4.0.5 on 2022-06-10 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='lithograph',
            new_name='lithography',
        ),
        migrations.RemoveField(
            model_name='product',
            name='core_family',
        ),
        migrations.RemoveField(
            model_name='product',
            name='manufacture',
        ),
        migrations.AddField(
            model_name='product',
            name='code_name',
            field=models.CharField(choices=[('AL', 'Alder Lake'), ('RL', 'Rocket Lake'), ('SB', 'Sandy Bridge'), ('IB', 'Ivy Bridge'), ('H', 'Haswell'), ('B', 'Broadwell'), ('SL', 'Skylake'), ('CL', 'Coffe Lake'), ('KL', 'Kaby Lake'), ('GL', 'Gemini Lake'), ('WL', 'Whiskey Lake'), ('TL', 'Tiger Lake'), ('LF', 'Lakefield'), ('CL', 'Cascade Lake'), ('CO', 'Comet Lake'), ('RL', 'Rocket Lake'), ('D', 'Denverton')], default=3, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturer',
            field=models.CharField(choices=[('IN', 'Intel'), ('AM', 'AMD')], default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='cores',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('4', '4'), ('6', '6'), ('8', '8'), ('10', '10'), ('12', '12'), ('14', '14'), ('16', '16'), ('18', '18')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='tdp',
            field=models.IntegerField(),
        ),
    ]
