# Generated by Django 4.0.5 on 2022-06-10 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_rename_lithograph_product_lithography_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cpu_cooler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('fanRpm', models.IntegerField()),
                ('noise_level', models.IntegerField()),
                ('color', models.CharField(max_length=20)),
                ('radiator_size', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('price', models.IntegerField()),
                ('manufacturer', models.CharField(max_length=40)),
                ('model', models.CharField(max_length=50)),
                ('part_number', models.CharField(max_length=40)),
                ('height', models.IntegerField()),
                ('Cpu_socket_supported', models.CharField(max_length=40)),
                ('water_cooled', models.BooleanField(verbose_name='yes')),
                ('fan_less', models.BooleanField(verbose_name='yes')),
            ],
        ),
        migrations.CreateModel(
            name='Mother_board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('socket_cpu', models.CharField(max_length=40)),
                ('form_factor', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=10)),
                ('rating', models.IntegerField(max_length=5)),
                ('manufacturer', models.CharField(max_length=40)),
                ('part_number', models.CharField(max_length=40)),
                ('chip_set', models.CharField(max_length=30)),
                ('memory_type', models.CharField(max_length=23)),
                ('sli_cross_fire', models.BooleanField(verbose_name='yes')),
            ],
        ),
        migrations.RenameField(
            model_name='product',
            old_name='performance',
            new_name='performance_L1_cache',
        ),
        migrations.AddField(
            model_name='product',
            name='part_number',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='performance_L2_cache',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='performance_L3_cache',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.IntegerField(default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='simultaneous_multiprocessor',
            field=models.BooleanField(default=1, verbose_name='yes'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(),
        ),
    ]
